/**
 * Static country code data — no API dependency.
 * Flags use emoji characters rendered directly in the UI (no images needed).
 * Shape matches the old API response: { country_code, name, image }
 * The `image` field contains the flag emoji string for backwards compatibility.
 */

interface CountryCode {
  country_code: string;
  name: string;
  image: string;
}

// Convert ISO country code to flag emoji
function flag(iso: string): string {
  return iso
    .toUpperCase()
    .split('')
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('');
}

export const staticCountryCodes: CountryCode[] = [
  // GCC (primary market) — listed first for quick access
  { country_code: '+973', name: 'Bahrain', image: flag('BH') },
  { country_code: '+965', name: 'Kuwait', image: flag('KW') },
  { country_code: '+968', name: 'Oman', image: flag('OM') },
  { country_code: '+974', name: 'Qatar', image: flag('QA') },
  { country_code: '+966', name: 'Saudi Arabia', image: flag('SA') },
  { country_code: '+971', name: 'United Arab Emirates', image: flag('AE') },
  // All other countries (alphabetical)
  { country_code: '+93', name: 'Afghanistan', image: flag('AF') },
  { country_code: '+355', name: 'Albania', image: flag('AL') },
  { country_code: '+213', name: 'Algeria', image: flag('DZ') },
  { country_code: '+1684', name: 'American Samoa', image: flag('AS') },
  { country_code: '+376', name: 'Andorra', image: flag('AD') },
  { country_code: '+244', name: 'Angola', image: flag('AO') },
  { country_code: '+1268', name: 'Antigua And Barbuda', image: flag('AG') },
  { country_code: '+54', name: 'Argentina', image: flag('AR') },
  { country_code: '+374', name: 'Armenia', image: flag('AM') },
  { country_code: '+61', name: 'Australia', image: flag('AU') },
  { country_code: '+43', name: 'Austria', image: flag('AT') },
  { country_code: '+994', name: 'Azerbaijan', image: flag('AZ') },
  { country_code: '+1242', name: 'Bahamas', image: flag('BS') },
  { country_code: '+880', name: 'Bangladesh', image: flag('BD') },
  { country_code: '+1246', name: 'Barbados', image: flag('BB') },
  { country_code: '+375', name: 'Belarus', image: flag('BY') },
  { country_code: '+32', name: 'Belgium', image: flag('BE') },
  { country_code: '+501', name: 'Belize', image: flag('BZ') },
  { country_code: '+229', name: 'Benin', image: flag('BJ') },
  { country_code: '+1441', name: 'Bermuda', image: flag('BM') },
  { country_code: '+975', name: 'Bhutan', image: flag('BT') },
  { country_code: '+591', name: 'Bolivia', image: flag('BO') },
  { country_code: '+387', name: 'Bosnia & Herzegovina', image: flag('BA') },
  { country_code: '+267', name: 'Botswana', image: flag('BW') },
  { country_code: '+55', name: 'Brazil', image: flag('BR') },
  { country_code: '+673', name: 'Brunei', image: flag('BN') },
  { country_code: '+359', name: 'Bulgaria', image: flag('BG') },
  { country_code: '+226', name: 'Burkina Faso', image: flag('BF') },
  { country_code: '+257', name: 'Burundi', image: flag('BI') },
  { country_code: '+238', name: 'Cabo Verde', image: flag('CV') },
  { country_code: '+855', name: 'Cambodia', image: flag('KH') },
  { country_code: '+237', name: 'Cameroon', image: flag('CM') },
  { country_code: '+1', name: 'Canada', image: flag('CA') },
  { country_code: '+236', name: 'Central African Republic', image: flag('CF') },
  { country_code: '+235', name: 'Chad', image: flag('TD') },
  { country_code: '+56', name: 'Chile', image: flag('CL') },
  { country_code: '+86', name: 'China', image: flag('CN') },
  { country_code: '+57', name: 'Colombia', image: flag('CO') },
  { country_code: '+269', name: 'Comoros', image: flag('KM') },
  { country_code: '+242', name: 'Congo', image: flag('CG') },
  { country_code: '+243', name: 'Congo (DRC)', image: flag('CD') },
  { country_code: '+506', name: 'Costa Rica', image: flag('CR') },
  { country_code: '+225', name: "Cote d'Ivoire", image: flag('CI') },
  { country_code: '+385', name: 'Croatia', image: flag('HR') },
  { country_code: '+53', name: 'Cuba', image: flag('CU') },
  { country_code: '+357', name: 'Cyprus', image: flag('CY') },
  { country_code: '+420', name: 'Czech Republic', image: flag('CZ') },
  { country_code: '+45', name: 'Denmark', image: flag('DK') },
  { country_code: '+253', name: 'Djibouti', image: flag('DJ') },
  { country_code: '+1767', name: 'Dominica', image: flag('DM') },
  { country_code: '+1809', name: 'Dominican Republic', image: flag('DO') },
  { country_code: '+593', name: 'Ecuador', image: flag('EC') },
  { country_code: '+20', name: 'Egypt', image: flag('EG') },
  { country_code: '+503', name: 'El Salvador', image: flag('SV') },
  { country_code: '+240', name: 'Equatorial Guinea', image: flag('GQ') },
  { country_code: '+291', name: 'Eritrea', image: flag('ER') },
  { country_code: '+372', name: 'Estonia', image: flag('EE') },
  { country_code: '+251', name: 'Ethiopia', image: flag('ET') },
  { country_code: '+679', name: 'Fiji', image: flag('FJ') },
  { country_code: '+358', name: 'Finland', image: flag('FI') },
  { country_code: '+33', name: 'France', image: flag('FR') },
  { country_code: '+241', name: 'Gabon', image: flag('GA') },
  { country_code: '+220', name: 'Gambia', image: flag('GM') },
  { country_code: '+995', name: 'Georgia', image: flag('GE') },
  { country_code: '+49', name: 'Germany', image: flag('DE') },
  { country_code: '+233', name: 'Ghana', image: flag('GH') },
  { country_code: '+30', name: 'Greece', image: flag('GR') },
  { country_code: '+473', name: 'Grenada', image: flag('GD') },
  { country_code: '+502', name: 'Guatemala', image: flag('GT') },
  { country_code: '+224', name: 'Guinea', image: flag('GN') },
  { country_code: '+245', name: 'Guinea-Bissau', image: flag('GW') },
  { country_code: '+592', name: 'Guyana', image: flag('GY') },
  { country_code: '+509', name: 'Haiti', image: flag('HT') },
  { country_code: '+504', name: 'Honduras', image: flag('HN') },
  { country_code: '+852', name: 'Hong Kong', image: flag('HK') },
  { country_code: '+36', name: 'Hungary', image: flag('HU') },
  { country_code: '+354', name: 'Iceland', image: flag('IS') },
  { country_code: '+91', name: 'India', image: flag('IN') },
  { country_code: '+62', name: 'Indonesia', image: flag('ID') },
  { country_code: '+98', name: 'Iran', image: flag('IR') },
  { country_code: '+964', name: 'Iraq', image: flag('IQ') },
  { country_code: '+353', name: 'Ireland', image: flag('IE') },
  { country_code: '+972', name: 'Israel', image: flag('IL') },
  { country_code: '+39', name: 'Italy', image: flag('IT') },
  { country_code: '+1876', name: 'Jamaica', image: flag('JM') },
  { country_code: '+81', name: 'Japan', image: flag('JP') },
  { country_code: '+962', name: 'Jordan', image: flag('JO') },
  { country_code: '+7', name: 'Kazakhstan', image: flag('KZ') },
  { country_code: '+254', name: 'Kenya', image: flag('KE') },
  { country_code: '+686', name: 'Kiribati', image: flag('KI') },
  { country_code: '+82', name: 'South Korea', image: flag('KR') },
  { country_code: '+996', name: 'Kyrgyzstan', image: flag('KG') },
  { country_code: '+856', name: 'Laos', image: flag('LA') },
  { country_code: '+371', name: 'Latvia', image: flag('LV') },
  { country_code: '+961', name: 'Lebanon', image: flag('LB') },
  { country_code: '+266', name: 'Lesotho', image: flag('LS') },
  { country_code: '+231', name: 'Liberia', image: flag('LR') },
  { country_code: '+218', name: 'Libya', image: flag('LY') },
  { country_code: '+423', name: 'Liechtenstein', image: flag('LI') },
  { country_code: '+370', name: 'Lithuania', image: flag('LT') },
  { country_code: '+352', name: 'Luxembourg', image: flag('LU') },
  { country_code: '+853', name: 'Macao', image: flag('MO') },
  { country_code: '+389', name: 'North Macedonia', image: flag('MK') },
  { country_code: '+261', name: 'Madagascar', image: flag('MG') },
  { country_code: '+265', name: 'Malawi', image: flag('MW') },
  { country_code: '+60', name: 'Malaysia', image: flag('MY') },
  { country_code: '+960', name: 'Maldives', image: flag('MV') },
  { country_code: '+223', name: 'Mali', image: flag('ML') },
  { country_code: '+356', name: 'Malta', image: flag('MT') },
  { country_code: '+692', name: 'Marshall Islands', image: flag('MH') },
  { country_code: '+222', name: 'Mauritania', image: flag('MR') },
  { country_code: '+230', name: 'Mauritius', image: flag('MU') },
  { country_code: '+52', name: 'Mexico', image: flag('MX') },
  { country_code: '+691', name: 'Micronesia', image: flag('FM') },
  { country_code: '+373', name: 'Moldova', image: flag('MD') },
  { country_code: '+377', name: 'Monaco', image: flag('MC') },
  { country_code: '+976', name: 'Mongolia', image: flag('MN') },
  { country_code: '+382', name: 'Montenegro', image: flag('ME') },
  { country_code: '+212', name: 'Morocco', image: flag('MA') },
  { country_code: '+258', name: 'Mozambique', image: flag('MZ') },
  { country_code: '+95', name: 'Myanmar', image: flag('MM') },
  { country_code: '+264', name: 'Namibia', image: flag('NA') },
  { country_code: '+674', name: 'Nauru', image: flag('NR') },
  { country_code: '+977', name: 'Nepal', image: flag('NP') },
  { country_code: '+31', name: 'Netherlands', image: flag('NL') },
  { country_code: '+64', name: 'New Zealand', image: flag('NZ') },
  { country_code: '+505', name: 'Nicaragua', image: flag('NI') },
  { country_code: '+227', name: 'Niger', image: flag('NE') },
  { country_code: '+234', name: 'Nigeria', image: flag('NG') },
  { country_code: '+47', name: 'Norway', image: flag('NO') },
  { country_code: '+92', name: 'Pakistan', image: flag('PK') },
  { country_code: '+680', name: 'Palau', image: flag('PW') },
  { country_code: '+970', name: 'Palestine', image: flag('PS') },
  { country_code: '+507', name: 'Panama', image: flag('PA') },
  { country_code: '+675', name: 'Papua New Guinea', image: flag('PG') },
  { country_code: '+595', name: 'Paraguay', image: flag('PY') },
  { country_code: '+51', name: 'Peru', image: flag('PE') },
  { country_code: '+63', name: 'Philippines', image: flag('PH') },
  { country_code: '+48', name: 'Poland', image: flag('PL') },
  { country_code: '+351', name: 'Portugal', image: flag('PT') },
  { country_code: '+1787', name: 'Puerto Rico', image: flag('PR') },
  { country_code: '+40', name: 'Romania', image: flag('RO') },
  { country_code: '+7', name: 'Russia', image: flag('RU') },
  { country_code: '+250', name: 'Rwanda', image: flag('RW') },
  { country_code: '+1869', name: 'Saint Kitts And Nevis', image: flag('KN') },
  { country_code: '+1758', name: 'Saint Lucia', image: flag('LC') },
  { country_code: '+1784', name: 'Saint Vincent And The Grenadines', image: flag('VC') },
  { country_code: '+685', name: 'Samoa', image: flag('WS') },
  { country_code: '+378', name: 'San Marino', image: flag('SM') },
  { country_code: '+239', name: 'Sao Tome And Principe', image: flag('ST') },
  { country_code: '+221', name: 'Senegal', image: flag('SN') },
  { country_code: '+381', name: 'Serbia', image: flag('RS') },
  { country_code: '+248', name: 'Seychelles', image: flag('SC') },
  { country_code: '+232', name: 'Sierra Leone', image: flag('SL') },
  { country_code: '+65', name: 'Singapore', image: flag('SG') },
  { country_code: '+421', name: 'Slovakia', image: flag('SK') },
  { country_code: '+386', name: 'Slovenia', image: flag('SI') },
  { country_code: '+677', name: 'Solomon Islands', image: flag('SB') },
  { country_code: '+252', name: 'Somalia', image: flag('SO') },
  { country_code: '+27', name: 'South Africa', image: flag('ZA') },
  { country_code: '+211', name: 'South Sudan', image: flag('SS') },
  { country_code: '+34', name: 'Spain', image: flag('ES') },
  { country_code: '+94', name: 'Sri Lanka', image: flag('LK') },
  { country_code: '+249', name: 'Sudan', image: flag('SD') },
  { country_code: '+597', name: 'Suriname', image: flag('SR') },
  { country_code: '+268', name: 'Eswatini', image: flag('SZ') },
  { country_code: '+46', name: 'Sweden', image: flag('SE') },
  { country_code: '+41', name: 'Switzerland', image: flag('CH') },
  { country_code: '+963', name: 'Syria', image: flag('SY') },
  { country_code: '+886', name: 'Taiwan', image: flag('TW') },
  { country_code: '+992', name: 'Tajikistan', image: flag('TJ') },
  { country_code: '+255', name: 'Tanzania', image: flag('TZ') },
  { country_code: '+66', name: 'Thailand', image: flag('TH') },
  { country_code: '+670', name: 'Timor-Leste', image: flag('TL') },
  { country_code: '+228', name: 'Togo', image: flag('TG') },
  { country_code: '+676', name: 'Tonga', image: flag('TO') },
  { country_code: '+1868', name: 'Trinidad And Tobago', image: flag('TT') },
  { country_code: '+216', name: 'Tunisia', image: flag('TN') },
  { country_code: '+90', name: 'Turkey', image: flag('TR') },
  { country_code: '+993', name: 'Turkmenistan', image: flag('TM') },
  { country_code: '+688', name: 'Tuvalu', image: flag('TV') },
  { country_code: '+256', name: 'Uganda', image: flag('UG') },
  { country_code: '+380', name: 'Ukraine', image: flag('UA') },
  { country_code: '+44', name: 'United Kingdom', image: flag('GB') },
  { country_code: '+1', name: 'United States', image: flag('US') },
  { country_code: '+598', name: 'Uruguay', image: flag('UY') },
  { country_code: '+998', name: 'Uzbekistan', image: flag('UZ') },
  { country_code: '+678', name: 'Vanuatu', image: flag('VU') },
  { country_code: '+58', name: 'Venezuela', image: flag('VE') },
  { country_code: '+84', name: 'Vietnam', image: flag('VN') },
  { country_code: '+967', name: 'Yemen', image: flag('YE') },
  { country_code: '+260', name: 'Zambia', image: flag('ZM') },
  { country_code: '+263', name: 'Zimbabwe', image: flag('ZW') },
];
