/**
 * Static country code data — no API dependency.
 * Flag images use inline SVG data URIs generated from country ISO codes.
 * Shape matches the old API response: { country_code, name, image }
 */

interface CountryCode {
  country_code: string;
  name: string;
  image: string;
}

// Convert ISO country code to flag emoji, then to an SVG data URI for <Image> compatibility
function flagSvg(iso: string): string {
  const flag = iso
    .toUpperCase()
    .split('')
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="15"><text x="0" y="13" font-size="14">${flag}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

export const staticCountryCodes: CountryCode[] = [
  // GCC (primary market) — listed first for quick access
  { country_code: '+973', name: 'Bahrain', image: flagSvg('BH') },
  { country_code: '+965', name: 'Kuwait', image: flagSvg('KW') },
  { country_code: '+968', name: 'Oman', image: flagSvg('OM') },
  { country_code: '+974', name: 'Qatar', image: flagSvg('QA') },
  { country_code: '+966', name: 'Saudi Arabia', image: flagSvg('SA') },
  { country_code: '+971', name: 'United Arab Emirates', image: flagSvg('AE') },
  // All other countries (alphabetical)
  { country_code: '+93', name: 'Afghanistan', image: flagSvg('AF') },
  { country_code: '+355', name: 'Albania', image: flagSvg('AL') },
  { country_code: '+213', name: 'Algeria', image: flagSvg('DZ') },
  { country_code: '+1684', name: 'American Samoa', image: flagSvg('AS') },
  { country_code: '+376', name: 'Andorra', image: flagSvg('AD') },
  { country_code: '+244', name: 'Angola', image: flagSvg('AO') },
  { country_code: '+1268', name: 'Antigua And Barbuda', image: flagSvg('AG') },
  { country_code: '+54', name: 'Argentina', image: flagSvg('AR') },
  { country_code: '+374', name: 'Armenia', image: flagSvg('AM') },
  { country_code: '+61', name: 'Australia', image: flagSvg('AU') },
  { country_code: '+43', name: 'Austria', image: flagSvg('AT') },
  { country_code: '+994', name: 'Azerbaijan', image: flagSvg('AZ') },
  { country_code: '+1242', name: 'Bahamas', image: flagSvg('BS') },
  { country_code: '+880', name: 'Bangladesh', image: flagSvg('BD') },
  { country_code: '+1246', name: 'Barbados', image: flagSvg('BB') },
  { country_code: '+375', name: 'Belarus', image: flagSvg('BY') },
  { country_code: '+32', name: 'Belgium', image: flagSvg('BE') },
  { country_code: '+501', name: 'Belize', image: flagSvg('BZ') },
  { country_code: '+229', name: 'Benin', image: flagSvg('BJ') },
  { country_code: '+1441', name: 'Bermuda', image: flagSvg('BM') },
  { country_code: '+975', name: 'Bhutan', image: flagSvg('BT') },
  { country_code: '+591', name: 'Bolivia', image: flagSvg('BO') },
  { country_code: '+387', name: 'Bosnia & Herzegovina', image: flagSvg('BA') },
  { country_code: '+267', name: 'Botswana', image: flagSvg('BW') },
  { country_code: '+55', name: 'Brazil', image: flagSvg('BR') },
  { country_code: '+673', name: 'Brunei', image: flagSvg('BN') },
  { country_code: '+359', name: 'Bulgaria', image: flagSvg('BG') },
  { country_code: '+226', name: 'Burkina Faso', image: flagSvg('BF') },
  { country_code: '+257', name: 'Burundi', image: flagSvg('BI') },
  { country_code: '+238', name: 'Cabo Verde', image: flagSvg('CV') },
  { country_code: '+855', name: 'Cambodia', image: flagSvg('KH') },
  { country_code: '+237', name: 'Cameroon', image: flagSvg('CM') },
  { country_code: '+1', name: 'Canada', image: flagSvg('CA') },
  { country_code: '+236', name: 'Central African Republic', image: flagSvg('CF') },
  { country_code: '+235', name: 'Chad', image: flagSvg('TD') },
  { country_code: '+56', name: 'Chile', image: flagSvg('CL') },
  { country_code: '+86', name: 'China', image: flagSvg('CN') },
  { country_code: '+57', name: 'Colombia', image: flagSvg('CO') },
  { country_code: '+269', name: 'Comoros', image: flagSvg('KM') },
  { country_code: '+242', name: 'Congo', image: flagSvg('CG') },
  { country_code: '+243', name: 'Congo (DRC)', image: flagSvg('CD') },
  { country_code: '+506', name: 'Costa Rica', image: flagSvg('CR') },
  { country_code: '+225', name: "Cote d'Ivoire", image: flagSvg('CI') },
  { country_code: '+385', name: 'Croatia', image: flagSvg('HR') },
  { country_code: '+53', name: 'Cuba', image: flagSvg('CU') },
  { country_code: '+357', name: 'Cyprus', image: flagSvg('CY') },
  { country_code: '+420', name: 'Czech Republic', image: flagSvg('CZ') },
  { country_code: '+45', name: 'Denmark', image: flagSvg('DK') },
  { country_code: '+253', name: 'Djibouti', image: flagSvg('DJ') },
  { country_code: '+1767', name: 'Dominica', image: flagSvg('DM') },
  { country_code: '+1809', name: 'Dominican Republic', image: flagSvg('DO') },
  { country_code: '+593', name: 'Ecuador', image: flagSvg('EC') },
  { country_code: '+20', name: 'Egypt', image: flagSvg('EG') },
  { country_code: '+503', name: 'El Salvador', image: flagSvg('SV') },
  { country_code: '+240', name: 'Equatorial Guinea', image: flagSvg('GQ') },
  { country_code: '+291', name: 'Eritrea', image: flagSvg('ER') },
  { country_code: '+372', name: 'Estonia', image: flagSvg('EE') },
  { country_code: '+251', name: 'Ethiopia', image: flagSvg('ET') },
  { country_code: '+679', name: 'Fiji', image: flagSvg('FJ') },
  { country_code: '+358', name: 'Finland', image: flagSvg('FI') },
  { country_code: '+33', name: 'France', image: flagSvg('FR') },
  { country_code: '+241', name: 'Gabon', image: flagSvg('GA') },
  { country_code: '+220', name: 'Gambia', image: flagSvg('GM') },
  { country_code: '+995', name: 'Georgia', image: flagSvg('GE') },
  { country_code: '+49', name: 'Germany', image: flagSvg('DE') },
  { country_code: '+233', name: 'Ghana', image: flagSvg('GH') },
  { country_code: '+30', name: 'Greece', image: flagSvg('GR') },
  { country_code: '+473', name: 'Grenada', image: flagSvg('GD') },
  { country_code: '+502', name: 'Guatemala', image: flagSvg('GT') },
  { country_code: '+224', name: 'Guinea', image: flagSvg('GN') },
  { country_code: '+245', name: 'Guinea-Bissau', image: flagSvg('GW') },
  { country_code: '+592', name: 'Guyana', image: flagSvg('GY') },
  { country_code: '+509', name: 'Haiti', image: flagSvg('HT') },
  { country_code: '+504', name: 'Honduras', image: flagSvg('HN') },
  { country_code: '+852', name: 'Hong Kong', image: flagSvg('HK') },
  { country_code: '+36', name: 'Hungary', image: flagSvg('HU') },
  { country_code: '+354', name: 'Iceland', image: flagSvg('IS') },
  { country_code: '+91', name: 'India', image: flagSvg('IN') },
  { country_code: '+62', name: 'Indonesia', image: flagSvg('ID') },
  { country_code: '+98', name: 'Iran', image: flagSvg('IR') },
  { country_code: '+964', name: 'Iraq', image: flagSvg('IQ') },
  { country_code: '+353', name: 'Ireland', image: flagSvg('IE') },
  { country_code: '+972', name: 'Israel', image: flagSvg('IL') },
  { country_code: '+39', name: 'Italy', image: flagSvg('IT') },
  { country_code: '+1876', name: 'Jamaica', image: flagSvg('JM') },
  { country_code: '+81', name: 'Japan', image: flagSvg('JP') },
  { country_code: '+962', name: 'Jordan', image: flagSvg('JO') },
  { country_code: '+7', name: 'Kazakhstan', image: flagSvg('KZ') },
  { country_code: '+254', name: 'Kenya', image: flagSvg('KE') },
  { country_code: '+686', name: 'Kiribati', image: flagSvg('KI') },
  { country_code: '+82', name: 'South Korea', image: flagSvg('KR') },
  { country_code: '+996', name: 'Kyrgyzstan', image: flagSvg('KG') },
  { country_code: '+856', name: 'Laos', image: flagSvg('LA') },
  { country_code: '+371', name: 'Latvia', image: flagSvg('LV') },
  { country_code: '+961', name: 'Lebanon', image: flagSvg('LB') },
  { country_code: '+266', name: 'Lesotho', image: flagSvg('LS') },
  { country_code: '+231', name: 'Liberia', image: flagSvg('LR') },
  { country_code: '+218', name: 'Libya', image: flagSvg('LY') },
  { country_code: '+423', name: 'Liechtenstein', image: flagSvg('LI') },
  { country_code: '+370', name: 'Lithuania', image: flagSvg('LT') },
  { country_code: '+352', name: 'Luxembourg', image: flagSvg('LU') },
  { country_code: '+853', name: 'Macao', image: flagSvg('MO') },
  { country_code: '+389', name: 'North Macedonia', image: flagSvg('MK') },
  { country_code: '+261', name: 'Madagascar', image: flagSvg('MG') },
  { country_code: '+265', name: 'Malawi', image: flagSvg('MW') },
  { country_code: '+60', name: 'Malaysia', image: flagSvg('MY') },
  { country_code: '+960', name: 'Maldives', image: flagSvg('MV') },
  { country_code: '+223', name: 'Mali', image: flagSvg('ML') },
  { country_code: '+356', name: 'Malta', image: flagSvg('MT') },
  { country_code: '+692', name: 'Marshall Islands', image: flagSvg('MH') },
  { country_code: '+222', name: 'Mauritania', image: flagSvg('MR') },
  { country_code: '+230', name: 'Mauritius', image: flagSvg('MU') },
  { country_code: '+52', name: 'Mexico', image: flagSvg('MX') },
  { country_code: '+691', name: 'Micronesia', image: flagSvg('FM') },
  { country_code: '+373', name: 'Moldova', image: flagSvg('MD') },
  { country_code: '+377', name: 'Monaco', image: flagSvg('MC') },
  { country_code: '+976', name: 'Mongolia', image: flagSvg('MN') },
  { country_code: '+382', name: 'Montenegro', image: flagSvg('ME') },
  { country_code: '+212', name: 'Morocco', image: flagSvg('MA') },
  { country_code: '+258', name: 'Mozambique', image: flagSvg('MZ') },
  { country_code: '+95', name: 'Myanmar', image: flagSvg('MM') },
  { country_code: '+264', name: 'Namibia', image: flagSvg('NA') },
  { country_code: '+674', name: 'Nauru', image: flagSvg('NR') },
  { country_code: '+977', name: 'Nepal', image: flagSvg('NP') },
  { country_code: '+31', name: 'Netherlands', image: flagSvg('NL') },
  { country_code: '+64', name: 'New Zealand', image: flagSvg('NZ') },
  { country_code: '+505', name: 'Nicaragua', image: flagSvg('NI') },
  { country_code: '+227', name: 'Niger', image: flagSvg('NE') },
  { country_code: '+234', name: 'Nigeria', image: flagSvg('NG') },
  { country_code: '+47', name: 'Norway', image: flagSvg('NO') },
  { country_code: '+92', name: 'Pakistan', image: flagSvg('PK') },
  { country_code: '+680', name: 'Palau', image: flagSvg('PW') },
  { country_code: '+970', name: 'Palestine', image: flagSvg('PS') },
  { country_code: '+507', name: 'Panama', image: flagSvg('PA') },
  { country_code: '+675', name: 'Papua New Guinea', image: flagSvg('PG') },
  { country_code: '+595', name: 'Paraguay', image: flagSvg('PY') },
  { country_code: '+51', name: 'Peru', image: flagSvg('PE') },
  { country_code: '+63', name: 'Philippines', image: flagSvg('PH') },
  { country_code: '+48', name: 'Poland', image: flagSvg('PL') },
  { country_code: '+351', name: 'Portugal', image: flagSvg('PT') },
  { country_code: '+1787', name: 'Puerto Rico', image: flagSvg('PR') },
  { country_code: '+40', name: 'Romania', image: flagSvg('RO') },
  { country_code: '+7', name: 'Russia', image: flagSvg('RU') },
  { country_code: '+250', name: 'Rwanda', image: flagSvg('RW') },
  { country_code: '+1869', name: 'Saint Kitts And Nevis', image: flagSvg('KN') },
  { country_code: '+1758', name: 'Saint Lucia', image: flagSvg('LC') },
  { country_code: '+1784', name: 'Saint Vincent And The Grenadines', image: flagSvg('VC') },
  { country_code: '+685', name: 'Samoa', image: flagSvg('WS') },
  { country_code: '+378', name: 'San Marino', image: flagSvg('SM') },
  { country_code: '+239', name: 'Sao Tome And Principe', image: flagSvg('ST') },
  { country_code: '+221', name: 'Senegal', image: flagSvg('SN') },
  { country_code: '+381', name: 'Serbia', image: flagSvg('RS') },
  { country_code: '+248', name: 'Seychelles', image: flagSvg('SC') },
  { country_code: '+232', name: 'Sierra Leone', image: flagSvg('SL') },
  { country_code: '+65', name: 'Singapore', image: flagSvg('SG') },
  { country_code: '+421', name: 'Slovakia', image: flagSvg('SK') },
  { country_code: '+386', name: 'Slovenia', image: flagSvg('SI') },
  { country_code: '+677', name: 'Solomon Islands', image: flagSvg('SB') },
  { country_code: '+252', name: 'Somalia', image: flagSvg('SO') },
  { country_code: '+27', name: 'South Africa', image: flagSvg('ZA') },
  { country_code: '+211', name: 'South Sudan', image: flagSvg('SS') },
  { country_code: '+34', name: 'Spain', image: flagSvg('ES') },
  { country_code: '+94', name: 'Sri Lanka', image: flagSvg('LK') },
  { country_code: '+249', name: 'Sudan', image: flagSvg('SD') },
  { country_code: '+597', name: 'Suriname', image: flagSvg('SR') },
  { country_code: '+268', name: 'Eswatini', image: flagSvg('SZ') },
  { country_code: '+46', name: 'Sweden', image: flagSvg('SE') },
  { country_code: '+41', name: 'Switzerland', image: flagSvg('CH') },
  { country_code: '+963', name: 'Syria', image: flagSvg('SY') },
  { country_code: '+886', name: 'Taiwan', image: flagSvg('TW') },
  { country_code: '+992', name: 'Tajikistan', image: flagSvg('TJ') },
  { country_code: '+255', name: 'Tanzania', image: flagSvg('TZ') },
  { country_code: '+66', name: 'Thailand', image: flagSvg('TH') },
  { country_code: '+670', name: 'Timor-Leste', image: flagSvg('TL') },
  { country_code: '+228', name: 'Togo', image: flagSvg('TG') },
  { country_code: '+676', name: 'Tonga', image: flagSvg('TO') },
  { country_code: '+1868', name: 'Trinidad And Tobago', image: flagSvg('TT') },
  { country_code: '+216', name: 'Tunisia', image: flagSvg('TN') },
  { country_code: '+90', name: 'Turkey', image: flagSvg('TR') },
  { country_code: '+993', name: 'Turkmenistan', image: flagSvg('TM') },
  { country_code: '+688', name: 'Tuvalu', image: flagSvg('TV') },
  { country_code: '+256', name: 'Uganda', image: flagSvg('UG') },
  { country_code: '+380', name: 'Ukraine', image: flagSvg('UA') },
  { country_code: '+44', name: 'United Kingdom', image: flagSvg('GB') },
  { country_code: '+1', name: 'United States', image: flagSvg('US') },
  { country_code: '+598', name: 'Uruguay', image: flagSvg('UY') },
  { country_code: '+998', name: 'Uzbekistan', image: flagSvg('UZ') },
  { country_code: '+678', name: 'Vanuatu', image: flagSvg('VU') },
  { country_code: '+58', name: 'Venezuela', image: flagSvg('VE') },
  { country_code: '+84', name: 'Vietnam', image: flagSvg('VN') },
  { country_code: '+967', name: 'Yemen', image: flagSvg('YE') },
  { country_code: '+260', name: 'Zambia', image: flagSvg('ZM') },
  { country_code: '+263', name: 'Zimbabwe', image: flagSvg('ZW') },
];
