export const pricingBusinessCard = [
  {
    title: 'Basic',
    subTitle: '14 days try period',
    description:
      'Just starting out but want to build a solid customer base & brand and while growing their presence as a professional service provider',
    price: '50',
    priceYear: '42',
    optionPlus: '',
    options: [
      '3 User / Calendar',
      '1 Branch/location',
      '1 Country ',
      'Unlimited bookings',
      'Themed Profile site with Social Links & Booking Feature',
      'Sales Management (POS)',
      'Client Management',
      'Mobile & Desktop App',
      'General Reports',
      'Customer Reviews Management',
      'In App & Email Notifications',
      'WhatsApp Notifications',
      'Portfolio of services',
      'Social Media Daisy Link',
      'Phone Contacts Syncing',
      'Google Calendar',
      'Basic Customer Support',
    ],
  },
  {
    title: 'Growth',
    subTitle: '14 days try period',
    description:
      'Ideal for Solo Experienced Professionals that want to provide an exceptional experience to their customers',
    price: '150',
    priceYear: '128',
    optionPlus: 'Basic',
    options: [
      '8 User / Calendar',
      '2 Branch/location',
      '1 Country ',
      'Unlimited bookings',
      'Automated reminders',
      'Subscription packages',
      'Online Payments',
      'Enforce Cancellation Fees & Refunds',
      'App Elastic search visibility',
      'Marketplace App visibility',
      'Customer Reviews & Feedback',
      'Priority Customer Support',
    ],
  },
  {
    title: 'Business',
    subTitle: '14 days try period',
    description:
      'Businesses with multiple branches or locations that are excellence oriented in service and customer service',
    price: '250',
    priceYear: '208',
    optionPlus: 'Growth',
    options: [
      '12 User / Calendar',
      '5 Branch/location',
      '1 country ',
      'Advanced Analytics and Trends',
      'Free Data Migration',
      'Free Assisted Onboarding & Services Menu Setup',
    ],
  },
];
