import { I18nContent } from '../i18n';
import { LandingPageContent } from './scrollSections.types';

export const businessPageData: I18nContent<LandingPageContent> = {
  en: {
    titleFraque: 'Frequently Asked Question',
    growth: {
      title: 'Maximize Bookings, Engage New Clients, and Grow Your Business with The Daisy.',
      description:
        'Leverage our platform to drive bookings, attract high-value clients, and manage your operations seamlessly.',
      subtitle: 'MARKETPLACE',
      buttonLearn: 'GET THE APP',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/business/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'MARKETPLACE',
          text: 'Showcase Your Team, Boost Your Business',
          description:
            'Unlock new opportunities to grow your customer base and increase profits with ease.',
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'FEATURES',
          text: 'User-Friendly Design',
          description:
            'Effortlessly manage bookings on both mobile and desktop.',
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/integrations.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'AUTOMATION',
          text: 'Simplify and Automate',
          description:
            'Streamline payment processing, synchronize appointments, and automate routine tasks.',
        },
      },
      {
        sortId: 5,
        mainImage: '/images/pages/business/scroll/analytics.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'ANALYTICS',
          text: 'Insights to Drive Growth',
          description:
            'Powerful analytics to track performance, identify trends, and optimize your operations for success.',
        },
      },
    ],
  },

  ar: {
    titleFraque: 'أسئلة شائعة',
    growth: {
      title: 'زِد حجوزاتك، جذب عملاء جدد، ونمِّ عملك مع ذا ديزي.',
      description:
        'استفد من منصتنا لزيادة الحجوزات وجذب العملاء ذوي القيمة العالية وإدارة عملياتك بسلاسة.',
      subtitle: 'السوق العام',
      buttonLearn: 'احصل على التطبيق',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/business/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'السوق العام',
          text: 'وسّع نطاقك، أبهج العملاء، وزد من نمو عملك بسهولة',
          description:
            'وسّع نطاقك، أبهج العملاء، وزد من نمو عملك بسهولة',
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'المميزات',
          text: 'تصميم سهل الاستخدام، متاح عبر جميع الأجهزة، يتكامل مع أنظمتك الحالية',
          description:
            'تصميم سهل الاستخدام، متاح عبر جميع الأجهزة، يتكامل مع أنظمتك الحالية',
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/integrations.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'الأتمتة',
          text: 'بسط المدفوعات، مزامنة الجداول، وأتمتة مهامك اليومية',
          description:
            'بسط المدفوعات، مزامنة الجداول، وأتمتة مهامك اليومية',
        },
      },
      {
        sortId: 5,
        mainImage: '/images/pages/business/scroll/analytics.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'التحليلات',
          text: 'افتح رؤى مع تقارير الأداء لتحفيز النمو',
          description:
            'افتح رؤى مع تقارير الأداء لتحفيز النمو',
        },
      },
    ],
  },
};
