import { I18nContent } from '../i18n';
import { LandingPageContent } from './scrollSections.types';

export const businessPageData: I18nContent<LandingPageContent> = {
  en: {
    hero: {
      categoryLabel: 'FOR BUSINESS OWNERS',
      headline: 'Grow Your Beauty Business with AI-Powered Everything',
      subHeadline:
        'Replace 8 tools with one platform. AI receptionist, customer acquisition, booking, payments, and marketing — all with your brand, your way.',
      ctaText: 'Start Free Trial',
      ctaLink: '/get-the-app',
      answerBlock: {
        question: 'What is The Daisy for beauty businesses?',
        answer:
          'The Daisy is an AI-powered beauty business platform that combines booking management, customer acquisition, payments, staff scheduling, and marketing into one system. It replaces 8 separate tools with a single multilingual platform — currently supporting Arabic and English — featuring a 24/7 AI receptionist.',
      },
    },
    platformStrengths: {
      headline: 'One Platform Replaces Your Entire Tool Stack',
      subHeadline:
        'Stop paying for 8 separate tools. Daisy combines everything you need to run and grow your beauty business.',
      capabilities: [
        { label: 'AI Receptionist', description: '24/7 automated booking, payments, and customer service' },
        { label: 'Smart Booking', description: 'Intelligent scheduling that fills your calendar' },
        { label: 'Customer Acquisition', description: 'Marketplace, cashback, and marketing tools' },
        { label: 'Payments & Invoicing', description: 'Seamless transactions and financial tracking' },
        { label: 'Staff Management', description: 'Scheduling, permissions, and performance' },
        { label: 'Marketing Engine', description: 'Promotions, campaigns, and customer retention' },
        { label: 'Analytics Dashboard', description: 'Revenue trends, insights, and reporting' },
        { label: 'Brand Control', description: 'White-label everything with your brand' },
      ],
      stats: [
        { value: '8', context: 'tools in one platform' },
        { value: '24/7', context: 'AI receptionist' },
        { value: '10+', context: 'languages supported' },
      ],
    },
    titleFraque: 'Frequently Asked Questions',
    fallbackFaqs: [
      { question: 'How much does The Daisy cost?', answer: 'The Daisy offers flexible pricing tiers starting with a 14-day free trial. Visit our pricing page for detailed plan comparisons.' },
      { question: 'Can I migrate from my current booking system?', answer: 'Yes. Our onboarding team helps you migrate your client data, booking history, and preferences from your existing system at no extra cost.' },
      { question: 'Does The Daisy work in Arabic?', answer: 'Yes. The Daisy is fully multilingual with complete Arabic and English support, including RTL interface, Arabic customer communications, and a multilingual AI receptionist — with more languages on the way.' },
      { question: 'What is the AI receptionist?', answer: 'The AI receptionist handles customer inquiries, booking requests, and payments 24/7 — even outside business hours. It speaks both Arabic and English and learns your business preferences over time.' },
      { question: 'Is there a free trial?', answer: 'Yes. Every new business gets a 14-day free trial with full access to all features. No credit card required to start.' },
    ],
    growth: {
      title: 'Stop Paying for 8 Separate Tools',
      description:
        'Booking, marketing, payments, staff scheduling, customer acquisition, analytics, brand management, and AI reception — Daisy replaces them all. One subscription, one dashboard, one login.',
      subtitle: 'MARKETPLACE',
      buttonLearn: 'GET THE APP',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/business/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px 0px 24px 24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
          objectPosition: 'right',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Smart Booking',
          text: 'AI-Powered Appointment Management',
          description:
            'Let Daisy\'s AI receptionist handle bookings 24/7, so you never miss a customer.',
          listSub: [
            '24/7 AI booking assistant',
            'Automated reminders & confirmations',
            'Smart calendar management',
            'Multi-staff scheduling',
          ],
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px 24px 0px 24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
          objectPosition: 'bottom',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Customer Acquisition',
          text: '360° Customer Growth Engine',
          description:
            'Grow your client base without the guesswork.',
          listSub: [
            'Marketplace visibility to thousands of users',
            'Cashback incentives that drive repeat visits',
            'Integrated marketing campaigns',
            'Customer loyalty programs',
          ],
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/business/scroll/integrations.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Brand Control',
          text: 'Your Brand, Your Way',
          description:
            'Customize your booking page, notifications, and customer experience to match your brand.',
          listSub: [
            'Customizable booking page',
            'White-label communications',
            'Branded customer experience',
            'Custom domain support',
          ],
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/analytics.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Business Analytics',
          text: 'Data-Driven Decisions',
          description:
            'See which services, staff, and promotions drive revenue — and act on it.',
          listSub: [
            'Customer insights & trends',
            'Staff performance metrics',
            'Booking analytics dashboard',
            'Real-time revenue tracking',
          ],
        },
      },
      {
        sortId: 5,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '-40px',
          left: '0',
          width: '300px',
          height: '300px',
          opacity: 0.6,
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          opacity: 0.4,
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Get Started',
          text: 'Ready to Grow Your Business?',
          description:
            'Download The Daisy app and start managing your bookings, growing your customer base, and taking your business to the next level.',
        },
      },
    ],
  },

  ar: {
    hero: {
      categoryLabel: 'لأصحاب الأعمال',
      headline: 'طوّر أعمالك التجميلية مع الذكاء الاصطناعي',
      subHeadline:
        'استبدل 8 أدوات بمنصة واحدة. موظف استقبال ذكي، استقطاب العملاء، الحجوزات، المدفوعات، والتسويق — كل ذلك بعلامتك التجارية.',
      ctaText: 'ابدأ تجربتك المجانية',
      ctaLink: '/get-the-app',
      answerBlock: {
        question: 'ما هو ذا ديزي لأعمال التجميل؟',
        answer:
          'ذا ديزي هو منصة أعمال تجميل مدعومة بالذكاء الاصطناعي تجمع بين إدارة الحجوزات واستقطاب العملاء والمدفوعات وجدولة الموظفين والتسويق في نظام واحد. يستبدل 8 أدوات منفصلة بمنصة ثنائية اللغة (عربي/إنجليزي) مع موظف استقبال ذكي يعمل على مدار الساعة.',
      },
    },
    platformStrengths: {
      headline: 'منصة واحدة تحل محل جميع أدواتك',
      subHeadline:
        'توقف عن الدفع لـ 8 أدوات منفصلة. ديزي تجمع كل ما تحتاجه لإدارة وتنمية أعمالك في مجال التجميل.',
      capabilities: [
        { label: 'موظف استقبال ذكي', description: 'حجوزات ومدفوعات وخدمة عملاء آلية على مدار الساعة' },
        { label: 'حجز ذكي', description: 'جدولة ذكية تملأ تقويمك' },
        { label: 'استقطاب العملاء', description: 'سوق إلكتروني وكاش باك وأدوات تسويق' },
        { label: 'المدفوعات والفوترة', description: 'معاملات سلسة وتتبع مالي' },
        { label: 'إدارة الموظفين', description: 'جدولة وصلاحيات وأداء' },
        { label: 'محرك التسويق', description: 'عروض وحملات والاحتفاظ بالعملاء' },
        { label: 'لوحة التحليلات', description: 'اتجاهات الإيرادات والرؤى والتقارير' },
        { label: 'التحكم بالعلامة التجارية', description: 'كل شيء بعلامتك التجارية الخاصة' },
      ],
      stats: [
        { value: '8', context: 'أدوات في منصة واحدة' },
        { value: '24/7', context: 'موظف استقبال ذكي' },
        { value: '+10', context: 'لغة مدعومة' },
      ],
    },
    titleFraque: 'أسئلة شائعة',
    fallbackFaqs: [
      { question: 'كم تكلفة ذا ديزي؟', answer: 'تقدم ذا ديزي باقات أسعار مرنة تبدأ بتجربة مجانية لمدة 14 يومًا. زر صفحة الأسعار لمقارنة الباقات بالتفصيل.' },
      { question: 'هل يمكنني الانتقال من نظام الحجز الحالي؟', answer: 'نعم. يساعدك فريق الإعداد لدينا في نقل بيانات عملائك وسجل الحجوزات وتفضيلاتك من نظامك الحالي دون أي تكلفة إضافية.' },
      { question: 'هل يعمل ذا ديزي باللغة العربية؟', answer: 'نعم. ذا ديزي متعدد اللغات بالكامل مع دعم كامل للعربية والإنجليزية، بما في ذلك واجهة RTL واتصالات العملاء بالعربية وموظف استقبال ذكي متعدد اللغات — مع المزيد من اللغات قريبًا.' },
      { question: 'ما هو موظف الاستقبال الذكي؟', answer: 'يتعامل موظف الاستقبال الذكي مع استفسارات العملاء وطلبات الحجز والمدفوعات على مدار الساعة — حتى خارج ساعات العمل. يتحدث العربية والإنجليزية ويتعلم تفضيلات عملك بمرور الوقت.' },
      { question: 'هل هناك تجربة مجانية؟', answer: 'نعم. يحصل كل عمل جديد على تجربة مجانية لمدة 14 يومًا مع وصول كامل لجميع الميزات. لا حاجة لبطاقة ائتمان للبدء.' },
    ],
    growth: {
      title: 'توقف عن الدفع لـ 8 أدوات منفصلة',
      description:
        'الحجوزات، التسويق، المدفوعات، جدولة الموظفين، استقطاب العملاء، التحليلات، إدارة العلامة التجارية، والاستقبال الذكي — ديزي تستبدلهم جميعًا. اشتراك واحد، لوحة تحكم واحدة، تسجيل دخول واحد.',
      subtitle: 'السوق العام',
      buttonLearn: 'احصل على التطبيق',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/business/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'الحجز الذكي',
          text: 'إدارة المواعيد بالذكاء الاصطناعي',
          description:
            'دع مساعد ديزي الذكي يتولى الحجوزات على مدار الساعة، حتى لا تفوتك أي فرصة. أدِر تقويمك وجداول الموظفين وفترات الخدمة في مكان واحد.',
          listSub: [
            'مساعد حجز ذكي يعمل على مدار الساعة',
            'تذكيرات وتأكيدات تلقائية',
            'إدارة تقويم ذكية',
            'جدولة متعددة الموظفين',
          ],
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'اكتساب العملاء',
          text: 'محرك نمو العملاء 360°',
          description:
            'اجذب عملاء جدد من خلال سوقنا ومكافآت الاسترداد النقدي وأدوات التسويق المدمجة. نمِّ قاعدة عملائك دون تخمين.',
          listSub: [
            'ظهور في السوق أمام آلاف المستخدمين',
            'حوافز استرداد نقدي تدفع لتكرار الزيارات',
            'حملات تسويقية متكاملة',
            'برامج ولاء العملاء',
          ],
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/business/scroll/integrations.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'التحكم بالعلامة التجارية',
          text: 'علامتك التجارية، بأسلوبك',
          description:
            'حافظ على السيطرة الكاملة على هوية علامتك التجارية مع حلول العلامة البيضاء. خصص صفحة الحجز والإشعارات وتجربة العملاء لتتناسب مع علامتك.',
          listSub: [
            'صفحة حجز قابلة للتخصيص',
            'اتصالات بعلامتك التجارية',
            'تجربة عملاء مخصصة',
            'دعم النطاق المخصص',
          ],
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/analytics.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'تحليلات الأعمال',
          text: 'قرارات مبنية على البيانات',
          description:
            'اكتشف أي الخدمات والموظفين والعروض تحقق الإيرادات — واتخذ إجراءً.',
          listSub: [
            'تتبع الإيرادات في الوقت الفعلي',
            'رؤى واتجاهات العملاء',
            'مقاييس أداء الموظفين',
            'لوحة تحكم تحليلات الحجوزات',
          ],
        },
      },
      {
        sortId: 5,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '-40px',
          left: '0',
          width: '300px',
          height: '300px',
          opacity: 0.6,
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          opacity: 0.4,
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'ابدأ الآن',
          text: 'هل أنت مستعد لتنمية عملك؟',
          description:
            'حمّل تطبيق ديزي وابدأ في إدارة حجوزاتك وتنمية قاعدة عملائك والارتقاء بعملك.',
        },
      },
    ],
  },
};
