import { I18nContent } from '../i18n';
import { LandingPageContent } from './scrollSections.types';

export const customerPageData: I18nContent<LandingPageContent> = {
  en: {
    titleFraque: 'Frequently Asked Questions',
    growth: {
      title: 'Discover Premium Services, Book Effortlessly, and Elevate Your Experience with The Daisy.',
      description:
        'Unlock a world of premium beauty and wellness services...',
      subtitle: 'MARKETPLACE',
      buttonLearn: 'GET THE APP',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/customer/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/customer/scroll/home-screen.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Easy Booking',
          text: 'Book in Seconds',
          description:
            'Find and book beauty and wellness services near you in just a few taps. Browse salons, spas, and clinics with real-time availability.',
          listSub: [
            'Instant booking confirmation',
            'Real-time availability',
            'Browse by service or location',
            'Save your favorite places',
          ],
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/customer/scroll/experiences.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Cashback Rewards',
          text: 'Earn While You Glow',
          description:
            'Get cashback on every booking. The more you book, the more you earn. Use your rewards on future services or withdraw to your wallet.',
          listSub: [
            'Cashback on every booking',
            'Accumulate and redeem rewards',
            'Wallet management',
            'Exclusive member deals',
          ],
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/customer/scroll/booking-frame.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Verified Reviews',
          text: 'Trust What Others Say',
          description:
            'Read verified reviews from real customers to choose the best services. Share your experience and help the community make informed decisions.',
          listSub: [
            'Verified customer reviews',
            'Star ratings & photos',
            'Detailed service feedback',
            'Community-driven trust',
          ],
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/customer/scroll/rating.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Smart Reminders',
          text: 'Never Miss an Appointment',
          description:
            'Get timely reminders before your appointments. Manage, reschedule, or cancel your bookings easily from the app.',
          listSub: [
            'Automated appointment reminders',
            'Easy rescheduling',
            'Booking history at a glance',
            'Calendar sync',
          ],
        },
      },
      {
        sortId: 5,
        mainImage: '/images/pages/customer/scroll/home-screen.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '-40px',
          left: '0',
          width: '300px',
          height: '300px',
          opacity: 0.6,
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          opacity: 0.4,
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Get Started',
          text: 'Start Your Beauty Journey',
          description:
            'Download The Daisy app and discover premium beauty and wellness services near you. Book, earn cashback, and enjoy!',
        },
      },
    ],
  },

  ar: {
    titleFraque: 'أسئلة شائعة',
    growth: {
      title: 'اكتشف الخدمات المتميزة، احجز بسهولة، وارفع تجربتك مع ذا ديزي.',
      description:
        'افتح عالمًا من خدمات الجمال والعافية المتميزة...',
      subtitle: 'السوق العام',
      buttonLearn: 'احصل على التطبيق',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/customer/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/customer/scroll/home-screen.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'حجز سهل',
          text: 'احجزي في ثوانٍ',
          description:
            'ابحثي واحجزي خدمات التجميل والعافية القريبة منك بلمسات قليلة. تصفحي الصالونات والمنتجعات والعيادات مع التوفر الفوري.',
          listSub: [
            'تأكيد فوري للحجز',
            'توفر في الوقت الفعلي',
            'تصفح حسب الخدمة أو الموقع',
            'احفظي أماكنك المفضلة',
          ],
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/customer/scroll/experiences.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'مكافآت الاسترداد النقدي',
          text: 'اكسبي أثناء تألقك',
          description:
            'احصلي على استرداد نقدي على كل حجز. كلما حجزتِ أكثر، كسبتِ أكثر. استخدمي مكافآتك على الخدمات المستقبلية أو اسحبيها إلى محفظتك.',
          listSub: [
            'استرداد نقدي على كل حجز',
            'اجمعي واستبدلي المكافآت',
            'إدارة المحفظة',
            'عروض حصرية للأعضاء',
          ],
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/customer/scroll/booking-frame.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'تقييمات موثوقة',
          text: 'ثقي بما يقوله الآخرون',
          description:
            'اقرأي تقييمات موثوقة من عملاء حقيقيين لاختيار أفضل الخدمات. شاركي تجربتك وساعدي المجتمع في اتخاذ قرارات مدروسة.',
          listSub: [
            'تقييمات عملاء موثوقة',
            'تقييمات بالنجوم والصور',
            'ملاحظات مفصلة عن الخدمة',
            'ثقة مدعومة من المجتمع',
          ],
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/customer/scroll/rating.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'تذكيرات ذكية',
          text: 'لا تفوّتي أي موعد',
          description:
            'احصلي على تذكيرات في الوقت المناسب قبل مواعيدك. أديري وأعيدي جدولة أو ألغي حجوزاتك بسهولة من التطبيق.',
          listSub: [
            'تذكيرات تلقائية بالمواعيد',
            'إعادة جدولة سهلة',
            'سجل الحجوزات بنظرة واحدة',
            'مزامنة التقويم',
          ],
        },
      },
      {
        sortId: 5,
        mainImage: '/images/pages/customer/scroll/home-screen.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '-40px',
          left: '0',
          width: '300px',
          height: '300px',
          opacity: 0.6,
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          opacity: 0.4,
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'ابدأ الآن',
          text: 'ابدأ رحلة جمالك',
          description:
            'حمّل تطبيق ديزي واكتشف خدمات التجميل والعافية المتميزة بالقرب منك. احجز، واكسب استرداد نقدي، واستمتع!',
        },
      },
    ],
  },
};
