import { I18nContent } from '../i18n';
import { LandingPageContent } from './scrollSections.types';

export const customerPageData: I18nContent<LandingPageContent> = {
  en: {
    titleFraque: 'Frequently Asked Question',
    growth: {
      title: 'Discover Premium Services, Book Effortlessly, and Elevate Your Experience with The Daisy.',
      description:
        'Unlock a world of premium beauty and wellness services...',
      subtitle: 'MARKETPLACE',
      buttonLearn: 'GET THE APP',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/customer/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/customer/scroll/home-screen.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'MARKETPLACE',
          text: 'Curated Services To Guarantee Your Experience',
          description:
            'Explore trusted and verified service providers.',
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/customer/scroll/experiences.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'DISCOVER',
          text: 'Discover Top Providers',
          description:
            'Check out before-and-afters showing customer results.',
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/customer/scroll/booking-frame.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'BOOKINGS',
          text: 'Easily Manage Bookings',
          description:
            'Booking appointments has never been easier or faster.',
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/customer/scroll/rating.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'CASHBACK',
          text: 'Earn Cashback Rewards!',
          description:
            'Find great deals and earn cashback.',
        },
      },
    ],
  },

  ar: {
    titleFraque: 'أسئلة شائعة',
    growth: {
      title: 'اكتشف الخدمات المتميزة، احجز بسهولة، وارفع تجربتك مع ذا ديزي.',
      description:
        'افتح عالمًا من خدمات الجمال والعافية المتميزة...',
      subtitle: 'السوق العام',
      buttonLearn: 'احصل على التطبيق',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/customer/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/customer/scroll/home-screen.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'السوق العام',
          text: 'اختر خدمتك التالية بثقة، وضمان تجربتك الاستثنائية.',
          description:
            'اختر خدمتك التالية بثقة، وضمان تجربتك الاستثنائية.',
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/customer/scroll/experiences.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'اكتشف',
          text: 'اكتشف التجارب من أفضل مزودي الخدمات',
          description:
            'اكتشف التجارب من أفضل مزودي الخدمات',
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/customer/scroll/booking-frame.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'الحجوزات',
          text: 'إدارة حجوزاتك بسهولة بنقرة واحدة',
          description:
            'إدارة حجوزاتك بسهولة بنقرة واحدة',
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/customer/scroll/rating.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'الاسترداد النقدي',
          text: 'اكسب استرداد نقدي بينما تدلل نفسك!',
          description:
            'اكسب استرداد نقدي بينما تدلل نفسك!',
        },
      },
    ],
  },
};
