import { I18nContent } from '../i18n';
import { LandingPageContent } from './scrollSections.types';

export const professionalPageData: I18nContent<LandingPageContent> = {
  en: {
    titleFraque: 'Frequently Asked Question',
    growth: {
      title: 'Expand Your Clientele, Manage Your Schedule, and Build Your Brand with The Daisy.',
      description:
        'Grow your freelance business with ease...',
      subtitle: 'MARKETPLACE',
      buttonLearn: 'GET THE APP',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/professional/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/professional/scroll/staff-details.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'BRAND',
          text: 'Showcase Your Work, Elevate Your Brand',
          description:
            'Your gateway to building a stronger reputation.',
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'CLIENTS',
          text: 'Engage With New Clients',
          description:
            'Build stronger connections with tools designed to keep clients coming back.',
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/business/scroll/analytics.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'SCHEDULE',
          text: 'Control Your Schedule',
          description:
            'Efficiently manage your appointments with easy-to-use scheduling tools.',
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'GROWTH',
          text: 'Track Your Growth',
          description:
            'Stay on top of your revenue and profits.',
        },
      },
    ],
  },

  ar: {
    titleFraque: 'أسئلة شائعة',
    growth: {
      title: 'وسّع قاعدة عملائك، نظم جدولك، وابنِ علامتك التجارية مع ذا ديزي.',
      description:
        'نمِّ عملك الحر بسهولة...',
      subtitle: 'السوق العام',
      buttonLearn: 'احصل على التطبيق',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/professional/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/professional/scroll/staff-details.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'العلامة التجارية',
          text: 'ارتقِ بعلامتك الشخصية',
          description:
            'ارتقِ بعلامتك الشخصية',
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'العملاء',
          text: 'عزّز تفاعل العملاء ونمِّ سمعتك',
          description:
            'عزّز تفاعل العملاء ونمِّ سمعتك',
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/business/scroll/analytics.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'الجدول',
          text: 'تحكم في جدولك وزد إنتاجيتك',
          description:
            'تحكم في جدولك وزد إنتاجيتك',
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'النمو',
          text: 'تتبع نموك المالي واتخذ قرارات مستندة إلى البيانات',
          description:
            'تتبع نموك المالي واتخذ قرارات مستندة إلى البيانات',
        },
      },
    ],
  },
};
