import { I18nContent } from '../i18n';
import { LandingPageContent } from './scrollSections.types';

export const professionalPageData: I18nContent<LandingPageContent> = {
  en: {
    titleFraque: 'Frequently Asked Question',
    growth: {
      title: 'Expand Your Clientele, Manage Your Schedule, and Build Your Brand with The Daisy.',
      description:
        'Grow your freelance business with ease...',
      subtitle: 'MARKETPLACE',
      buttonLearn: 'GET THE APP',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/professional/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/professional/scroll/staff-details.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Flexible Schedule',
          text: 'Work on Your Terms',
          description:
            'Set your own hours and manage your availability with ease. Daisy gives you full control over when and where you work.',
          listSub: [
            'Set your own working hours',
            'Block time for personal commitments',
            'Real-time schedule updates',
            'Multi-location support',
          ],
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Client Management',
          text: 'Build Lasting Relationships',
          description:
            'Keep track of your clients, their preferences, and appointment history. Build stronger relationships and deliver personalized services.',
          listSub: [
            'Detailed client profiles',
            'Appointment history tracking',
            'Client preference notes',
            'Automated follow-ups',
          ],
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/business/scroll/analytics.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Earnings Tracker',
          text: 'Maximize Your Income',
          description:
            'Track your earnings in real-time, view detailed reports, and understand your revenue patterns. Stay on top of your finances effortlessly.',
          listSub: [
            'Real-time earnings dashboard',
            'Detailed payment reports',
            'Revenue trends & insights',
            'Commission tracking',
          ],
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Professional Profile',
          text: 'Showcase Your Expertise',
          description:
            'Build a professional profile that highlights your skills, experience, and client reviews. Stand out and attract more clients.',
          listSub: [
            'Portfolio showcase',
            'Client reviews & ratings',
            'Skill certifications display',
            'Service menu customization',
          ],
        },
      },
    ],
  },

  ar: {
    titleFraque: 'أسئلة شائعة',
    growth: {
      title: 'وسّع قاعدة عملائك، نظم جدولك، وابنِ علامتك التجارية مع ذا ديزي.',
      description:
        'نمِّ عملك الحر بسهولة...',
      subtitle: 'السوق العام',
      buttonLearn: 'احصل على التطبيق',
      buttonLink: '/get-the-app',
      imageUrl: '/images/pages/professional/growth.png',
    },
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/professional/scroll/staff-details.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'جدول مرن',
          text: 'اعمل بشروطك',
          description:
            'حدد ساعات عملك وأدِر توافرك بسهولة. ديزي يمنحك تحكمًا كاملاً في متى وأين تعمل.',
          listSub: [
            'حدد ساعات عملك الخاصة',
            'خصص وقتًا لالتزاماتك الشخصية',
            'تحديثات الجدول في الوقت الفعلي',
            'دعم المواقع المتعددة',
          ],
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'إدارة العملاء',
          text: 'ابنِ علاقات دائمة',
          description:
            'تابع عملاءك وتفضيلاتهم وسجل مواعيدهم. ابنِ علاقات أقوى وقدّم خدمات مخصصة.',
          listSub: [
            'ملفات تعريف مفصلة للعملاء',
            'تتبع سجل المواعيد',
            'ملاحظات تفضيلات العملاء',
            'متابعات تلقائية',
          ],
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/business/scroll/analytics.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        secondBg: '/images/pages/business/scroll/stars.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'تتبع الأرباح',
          text: 'حقق أقصى دخل لك',
          description:
            'تتبع أرباحك في الوقت الفعلي، واعرض تقارير مفصلة، وافهم أنماط إيراداتك. ابقَ على اطلاع بأمورك المالية بسهولة.',
          listSub: [
            'لوحة أرباح في الوقت الفعلي',
            'تقارير دفع مفصلة',
            'اتجاهات ورؤى الإيرادات',
            'تتبع العمولات',
          ],
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/device-mockups.png',
        firstBg: '/images/pages/business/scroll/leaf-bg.png',
        styleMainPictureJSON: {
          position: 'absolute',
          bottom: '0',
          right: '50%',
          transform: 'translateX(50%)',
          width: '50%',
          maxWidth: '300px',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'الملف المهني',
          text: 'اعرض خبراتك',
          description:
            'أنشئ ملفًا مهنيًا يبرز مهاراتك وخبراتك وتقييمات العملاء. تميّز واجذب المزيد من العملاء.',
          listSub: [
            'عرض معرض الأعمال',
            'تقييمات ومراجعات العملاء',
            'عرض الشهادات المهنية',
            'تخصيص قائمة الخدمات',
          ],
        },
      },
    ],
  },
};
