import { I18nContent } from '../i18n';
import { LandingPageContent } from './scrollSections.types';

export const professionalPageData: I18nContent<LandingPageContent> = {
  en: {
    hero: {
      categoryLabel: 'FOR BEAUTY PROFESSIONALS',
      headline: 'Focus on Your Craft.\nDaisy Handles the Rest.',
      subHeadline:
        "Stop being your own receptionist. Daisy's AI handles your WhatsApp and Instagram messages, books appointments, and processes payments, while you focus on what you do best.",
      ctaText: 'Start Your Free Trial',
      ctaLink: '/start-free-trial/professional',
      trustLine: 'Free to join. No credit card required.',
      answerBlock: {
        question: 'What is The Daisy for beauty professionals?',
        answer:
          "The Daisy is an all-in-one app for beauty and wellness professionals. Its AI assistant handles WhatsApp and Instagram messages, bookings, and payments 24/7, so professionals can focus on providing exceptional services. Features flexible scheduling, multilingual support, and a marketplace for client discovery.",
      },
    },
    platformStrengths: {
      headline: 'Everything You Need in One App',
      subHeadline:
        'No more juggling between scheduling apps, payment tools, and messaging clients. Daisy brings it all together.',
      capabilities: [
        { label: 'AI Booking Assistant', description: 'Handles bookings and payments while you work' },
        { label: 'Flexible Scheduling', description: 'Set your own hours across multiple locations' },
        { label: 'Earnings Tracker', description: 'Track revenue in real-time with detailed breakdowns' },
        { label: 'Professional Profile', description: 'Showcase your work and attract new clients' },
        { label: 'Client Management', description: 'Build relationships with detailed client profiles' },
        { label: 'Smart Notifications', description: 'Appointment reminders that reduce no-shows' },
        { label: 'Calendar Sync', description: 'Sync with Google Calendar and other tools' },
        { label: 'Marketplace Visibility', description: 'Customers find you when searching nearby' },
      ],
      stats: [
        { value: '1', context: 'app for everything' },
        { value: '24/7', context: 'AI-powered booking' },
        { value: '10+', context: 'languages supported' },
      ],
    },
    socialProofStats: [
      { value: '0%', context: 'commission on your existing clients' },
      { value: '24/7', context: 'AI handles bookings while you work' },
      { value: '10+', context: 'languages supported' },
    ],
    howItWorks: {
      title: 'How It Works',
      steps: [
        { title: 'Sign up and tell us about yourself', description: 'Takes 5 minutes. Set your services, availability, and pricing.' },
        { title: 'Our team helps you get set up', description: 'We configure your profile, set up your AI assistant, and walk you through everything.' },
        { title: 'Go live. Focus on your clients.', description: 'Daisy handles your bookings. You handle your craft.' },
      ],
    },
    pricingHook: {
      headline: 'Free to Join. Zero Risk.',
      body: "Create your profile and start accepting bookings at no cost. Premium features available through affordable plans. Daisy doesn't just manage your schedule. It learns your clients' preferences, personalizes their booking experience, and makes sure you never miss an inquiry. Commission only on new clients who find you through the Daisy marketplace, your existing clients always pay zero commission.",
      ctaText: 'Get Listed for Free',
      ctaLink: '/start-free-trial/professional',
      pricingLinkText: 'See full pricing details →',
      pricingLinkHref: '/pricing',
    },
    inlineCtas: {
      afterScroll: {
        headline: 'Ready to stop being your own receptionist?',
        ctaText: 'Start Your Free Trial',
        ctaLink: '/start-free-trial/professional',
      },
      afterFeatures: {
        headline: 'Start Your Free Trial',
        ctaText: 'Start Your Free Trial',
        ctaLink: '/start-free-trial/professional',
        secondaryLinkText: 'Explore all features →',
        secondaryLinkHref: '/features/professional',
      },
    },
    titleFraque: 'Frequently Asked Questions',
    fallbackFaqs: [
      { question: 'Is there a fee or commission?', answer: 'Joining is free. Commission is only charged on new clients who book you through the Daisy marketplace, your existing clients pay zero commission. Premium features available through affordable subscription tiers.' },
      { question: 'Do I need to work at a salon to join?', answer: 'No. Freelance professionals, independent stylists, mobile service providers, and salon-based professionals are all welcome.' },
      { question: 'How do customers find my profile?', answer: 'Your profile appears in the Daisy marketplace when customers search for beauty services in your area. The more complete your profile, the higher your visibility.' },
      { question: 'How does payment work?', answer: 'Your earnings are tracked in real-time in the app. Payments are processed securely and deposited to your bank account weekly. You can see exactly what you earned from each appointment.' },
    ],
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/professional/scroll/staff-details.webp',
        firstBg: '/images/pages/business/scroll/leaf-bg.webp',
        secondBg: '/images/pages/business/scroll/stars.webp',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          padding: '24px 24px 24px 24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
          objectPosition: 'center',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'A Client Messages You on WhatsApp',
          text: "You're Mid-Appointment. Daisy Answers.",
          description:
            "You're giving a haircut when a new client sends a WhatsApp message asking about your availability for highlights. Daisy responds instantly. You never even see the notification.",
          listSub: [
            'AI responds while you work',
            'Knows your services and prices',
            'Speaks their language',
          ],
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.webp',
        firstBg: '/images/pages/business/scroll/leaf-bg.webp',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          padding: '24px 24px 24px 24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
          objectPosition: 'center',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Booked Into Your Next Open Slot',
          text: 'No Missed Messages. No Back-and-Forth.',
          description:
            "Daisy checks your schedule, finds the next available slot, and confirms the booking. The client gets an instant confirmation. You find out when you're done with your current client.",
          listSub: [
            'Real-time schedule awareness',
            'Instant booking confirmation',
            'Zero interruption to your work',
          ],
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/business/scroll/analytics.webp',
        firstBg: '/images/pages/business/scroll/leaf-bg.webp',
        secondBg: '/images/pages/business/scroll/stars.webp',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          padding: '24px 24px 24px 24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
          objectPosition: 'center',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Paid Before They Sit Down',
          text: 'No Awkward Money Conversations',
          description:
            "The client pays through the app before their appointment. When they arrive, you just focus on the service.",
          listSub: [
            'In-app payment processing',
            'Deposit or full prepayment',
            'Automatic receipts',
          ],
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/device-mockups.webp',
        firstBg: '/images/pages/business/scroll/leaf-bg.webp',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          padding: '24px 24px 24px 24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
          objectPosition: 'center',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'Your Calendar, Always Up to Date',
          text: "Check Between Clients. Everything's There.",
          description:
            "When you check your phone between appointments, you see the new booking with all the details. The client is confirmed, paid, and knows exactly when to arrive. You didn't do a thing.",
          listSub: [
            'Synced to your calendar',
            'Client gets reminders',
            'Your earnings update in real-time',
          ],
        },
      },
    ],
  },

  ar: {
    hero: {
      categoryLabel: 'لمتخصصي التجميل',
      headline: 'ركّز على إبداعك.\nديزي تتولى الباقي.',
      subHeadline:
        'توقف عن كونك موظف استقبال نفسك. الذكاء الاصطناعي في ديزي يتولى رسائل واتساب وإنستغرام، يحجز المواعيد، ويعالج المدفوعات، بينما تركز على ما تتقنه.',
      ctaText: 'ابدأ تجربتك المجانية',
      ctaLink: '/start-free-trial/professional',
      trustLine: 'الانضمام مجاني. لا حاجة لبطاقة ائتمان.',
      answerBlock: {
        question: 'ما هو ذا ديزي لمتخصصي التجميل؟',
        answer:
          'ذا ديزي هو تطبيق شامل لمتخصصي التجميل والعافية. مساعده الذكي يتولى رسائل واتساب وإنستغرام والحجوزات والمدفوعات على مدار الساعة، حتى يتمكن المتخصصون من التركيز على تقديم خدمات استثنائية. يتميز بجدولة مرنة ودعم متعدد اللغات وسوق لاكتشاف العملاء.',
      },
    },
    platformStrengths: {
      headline: 'كل ما تحتاجه في تطبيق واحد',
      subHeadline:
        'لا مزيد من التنقل بين تطبيقات الجدولة وأدوات الدفع ومراسلة العملاء. ديزي تجمع كل شيء معًا.',
      capabilities: [
        { label: 'مساعد الحجز الذكي', description: 'يتولى الحجوزات والمدفوعات أثناء عملك' },
        { label: 'جدولة مرنة', description: 'حدد ساعات عملك عبر مواقع متعددة' },
        { label: 'متتبع الأرباح', description: 'تتبع الإيرادات في الوقت الفعلي مع تفاصيل دقيقة' },
        { label: 'الملف المهني', description: 'اعرض أعمالك واجذب عملاء جدد' },
        { label: 'إدارة العملاء', description: 'ابنِ علاقات مع ملفات عملاء مفصلة' },
        { label: 'إشعارات ذكية', description: 'تذكيرات بالمواعيد تقلل حالات عدم الحضور' },
        { label: 'مزامنة التقويم', description: 'مزامنة مع تقويم جوجل وأدوات أخرى' },
        { label: 'ظهور في السوق', description: 'العملاء يجدونك عند البحث بالقرب منهم' },
      ],
      stats: [
        { value: '1', context: 'تطبيق لكل شيء' },
        { value: '24/7', context: 'حجز مدعوم بالذكاء الاصطناعي' },
        { value: '+10', context: 'لغة مدعومة' },
      ],
    },
    socialProofStats: [
      { value: '0%', context: 'عمولة على عملائك الحاليين' },
      { value: '24/7', context: 'الذكاء الاصطناعي يدير الحجوزات أثناء عملك' },
      { value: '+10', context: 'لغة مدعومة' },
    ],
    howItWorks: {
      title: 'كيف يعمل',
      steps: [
        { title: 'سجّل وأخبرنا عن نفسك', description: 'يستغرق 5 دقائق. حدد خدماتك وتوافرك وأسعارك.' },
        { title: 'فريقنا يساعدك في الإعداد', description: 'نُعدّ ملفك الشخصي ونُجهّز مساعدك الذكي ونشرح لك كل شيء.' },
        { title: 'ابدأ العمل. ركّز على عملائك.', description: 'ديزي تتولى حجوزاتك. أنت تتولى إبداعك.' },
      ],
    },
    pricingHook: {
      headline: 'الانضمام مجاني. بدون أي مخاطر.',
      body: 'أنشئ ملفك الشخصي وابدأ بقبول الحجوزات بدون تكلفة. الميزات المتقدمة متاحة من خلال باقات بأسعار معقولة. ديزي لا تدير جدولك فحسب. بل تتعلم تفضيلات عملائك، وتُخصّص تجربة حجزهم، وتتأكد من عدم تفويت أي استفسار. العمولة فقط على العملاء الجدد الذين يجدونك عبر سوق ديزي، عملاؤك الحاليون، بدون أي عمولة دائمًا.',
      ctaText: 'سجّل مجانًا',
      ctaLink: '/start-free-trial/professional',
      pricingLinkText: 'اطلع على تفاصيل الأسعار الكاملة ←',
      pricingLinkHref: '/pricing',
    },
    inlineCtas: {
      afterScroll: {
        headline: 'مستعد للتوقف عن كونك موظف استقبال نفسك؟',
        ctaText: 'ابدأ تجربتك المجانية',
        ctaLink: '/start-free-trial/professional',
      },
      afterFeatures: {
        headline: 'ابدأ تجربتك المجانية',
        ctaText: 'ابدأ تجربتك المجانية',
        ctaLink: '/start-free-trial/professional',
        secondaryLinkText: 'استكشف جميع الميزات →',
        secondaryLinkHref: '/features/professional',
      },
    },
    titleFraque: 'أسئلة شائعة',
    fallbackFaqs: [
      { question: 'هل هناك رسوم أو عمولة؟', answer: 'الانضمام مجاني. العمولة تُفرض فقط على العملاء الجدد الذين يحجزون عبر سوق ديزي، عملاؤك الحاليون، بدون أي عمولة. الميزات المتقدمة متاحة من خلال باقات اشتراك بأسعار معقولة.' },
      { question: 'هل أحتاج للعمل في صالون للانضمام؟', answer: 'لا. المتخصصون المستقلون والمصممون المستقلون ومقدمو الخدمات المتنقلون والمتخصصون في الصالونات مرحب بهم جميعًا.' },
      { question: 'كيف يجد العملاء ملفي الشخصي؟', answer: 'يظهر ملفك الشخصي في سوق ديزي عندما يبحث العملاء عن خدمات التجميل في منطقتك. كلما كان ملفك أكثر اكتمالًا، زاد ظهورك.' },
      { question: 'كيف يعمل الدفع؟', answer: 'يتم تتبع أرباحك في الوقت الفعلي في التطبيق. تتم معالجة المدفوعات بشكل آمن وإيداعها في حسابك البنكي أسبوعيًا. يمكنك رؤية ما كسبته بالضبط من كل موعد.' },
    ],
    scrollSections: [
      {
        sortId: 1,
        mainImage: '/images/pages/professional/scroll/staff-details.webp',
        firstBg: '/images/pages/business/scroll/leaf-bg.webp',
        secondBg: '/images/pages/business/scroll/stars.webp',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'عميل يراسلك على واتساب',
          text: 'أنت في منتصف موعد. ديزي ترد.',
          description:
            'أنت تقص شعرًا عندما يرسل عميل جديد رسالة واتساب يسأل عن توفرك لتسليط الضوء. ديزي ترد فورًا. لم تلاحظ حتى الإشعار.',
          listSub: [
            'الذكاء الاصطناعي يرد أثناء عملك',
            'يعرف خدماتك وأسعارك',
            'يتحدث بلغتهم',
          ],
        },
      },
      {
        sortId: 2,
        mainImage: '/images/pages/business/scroll/schedule.webp',
        firstBg: '/images/pages/business/scroll/leaf-bg.webp',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'محجوز في أقرب وقت متاح',
          text: 'بدون رسائل فائتة. بدون تراسل متكرر.',
          description:
            'ديزي تتحقق من جدولك وتجد أقرب وقت متاح وتؤكد الحجز. العميل يحصل على تأكيد فوري. أنت تعرف عندما تنتهي من عميلك الحالي.',
          listSub: [
            'وعي بالجدول في الوقت الفعلي',
            'تأكيد حجز فوري',
            'بدون أي انقطاع في عملك',
          ],
        },
      },
      {
        sortId: 3,
        mainImage: '/images/pages/business/scroll/analytics.webp',
        firstBg: '/images/pages/business/scroll/leaf-bg.webp',
        secondBg: '/images/pages/business/scroll/stars.webp',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleSecondBgJSON: {
          position: 'absolute',
          top: '40px',
          right: '30px',
          width: '100px',
        },
        styleBgMobileSecond: {
          position: 'absolute',
          top: '-70px',
          right: '-70px',
          width: '200px',
          height: '200px',
          transform: 'rotate(180deg) scaleX(-1)',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'الدفع تم قبل جلوسهم',
          text: 'بدون محادثات محرجة عن المال',
          description:
            'العميل يدفع عبر التطبيق قبل موعده. عند وصوله، تركز فقط على الخدمة.',
          listSub: [
            'معالجة الدفع عبر التطبيق',
            'عربون أو دفع مسبق كامل',
            'إيصالات تلقائية',
          ],
        },
      },
      {
        sortId: 4,
        mainImage: '/images/pages/business/scroll/device-mockups.webp',
        firstBg: '/images/pages/business/scroll/leaf-bg.webp',
        styleMainPictureJSON: {
          position: 'absolute',
          padding: '24px',
          width: '100%',
          height: '100%',
          objectFit: 'contain',
        },
        styleFirstBgJSON: {
          position: 'absolute',
          bottom: '0',
          left: '0',
          width: '50%',
          maxWidth: '300px',
        },
        styleImageMobile: {
          position: 'absolute',
          width: '100%',
          height: '100%',
          bottom: '0',
          left: '40px',
        },
        mainImageWidth: 300,
        mainImageHeight: 500,
        infoScroll: {
          title: 'تقويمك محدّث دائمًا',
          text: 'تفقّد بين العملاء. كل شيء موجود.',
          description:
            'عندما تتفقد هاتفك بين المواعيد، ترى الحجز الجديد بكل التفاصيل. العميل مؤكد ودافع ويعرف بالضبط متى يصل. لم تفعل شيئًا.',
          listSub: [
            'مزامنة مع تقويمك',
            'العميل يحصل على تذكيرات',
            'أرباحك تتحدث في الوقت الفعلي',
          ],
        },
      },
    ],
  },
};
